version: '3.7'

services:
    NewsAnalyser:
        build:
            context: ./src/NewsAnalyser
        image: news-maker
        container_name: news-maker
        restart: unless-stopped

        command: ["python3", "main.py"]